version: '2'
services:
  mysql:
    image: mysql
    container_name: store-db
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
